### PR TITLE
Antha 2772 file series antha core

### PR DESCRIPTION
**Pull request by levitskovich**
Merged the recent changes from `master` including the `FileSeries` data type definition + changed `File` to `*File` (do I understand right that antha-core uses pointers to files?)

### CODE REVIEW

**Comment by msackman-synthace** [comment]
As discussed on slack, we suspect there need to be changes to migrate, both for the v1.2 json format, and for the simulate request protobuf format.

**Comment by msackman-synthace** [comment]
@levitskovich for testing the protobuf form: *if* you can create a workflow in the ui and run it (old world - not antha-core), then you should be able to grab the request.pb from execution details, or, failing that, if you have the job id then I can show you how to pull it out of the cloud storage stuff.

**Comment by levitskovich** [comment]
Ah, I see, thanks, I'll try doing this - I have an old-style workflow which I can upload to the UI and simulate there to get a request.pb

**Comment by levitskovich** [comment]
Protobuf migration seems to work as well.

Btw, do I understand that merging this is not going to affect non-antha-core simulations at ninja anyway? (remembering that Toby asked not to break ninja because of todays OXB demo)

**Comment by msackman-synthace** [comment]
> Btw, do I understand that merging this is not going to affect non-antha-core simulations at ninja anyway? (remembering that Toby asked not to break ninja because of todays OXB demo)

Yes, this will have no effect on non-antha-core simulations on ninja, don't worry!

**Pull request merged**
