### PR TITLE
New plate/fluidx700ul

### PR DESCRIPTION
**Pull request by chr1sgrant**

### CODE REVIEW

**Comment by x-anderson** [comment]
@chr1sgrant  Was going to test this physically, but the linked plate and the description (8x12 wells) does not appear to relate to any FLuidX plates we have in stock - possible we need to obtain these plates, or these may be other plates, but im not totally sure which ones.

**Comment by chr1sgrant** [comment]
there's a link to it in the comment: // http://fluidx.eu/0.7ml%2c-96-well-format-2d-barcoded-jacket-tube-with-external-thread.html
It's basically a rack with the small tubes.

**Comment by x-anderson** [comment]
OK, we dont have any of these here so would need to order one to finalise the physical testing - shall I do this?

**Comment by chr1sgrant** [comment]
[FluidXTest20180315165355.xlsx](https://github.com/antha-lang/antha/files/1819297/FluidXTest20180315165355.xlsx)

**Pull request merged**
