### PR TITLE
Add time and cumulative time estimates for prompts

### PR DESCRIPTION
**Pull request by haydnKing**
schema was missing "cumulative_time_estimate" and "time_estimate" for promptActions

### CODE REVIEW

**Comment by haydnKing** [comment]
Am busy running antha-tester manually to verify that this fix is correct

**Comment by haydnKing** [comment]
tests ran through successfully, should be good

**Comment by chr1sgrant** [comment]
Works for me with the bundle files I was having errors with previously

**Comment by mkonicek** [comment]
Nice!

**Pull request merged**
